name: ehignlasttwo
channels:
  - dglteam
  - pytorch
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - blas=1.0=mkl
  - brotli-python=1.1.0=py39h3d6467e_1
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.15.1=py39h7a31438_5
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=39.0.1=py39h079d5ae_0
  - cudatoolkit=11.3.1=hb98b00a_13
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.16.1=pyhd8ed1ab_1
  - freetype=2.12.1=h267a509_2
  - giflib=5.2.2=hd590300_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py39h376b7d2_1
  - gnutls=3.6.13=h85f3911_1
  - h2=4.1.0=pyhd8ed1ab_1
  - hpack=4.0.0=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=73.2=h59595ed_0
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=hfd0df8a_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libdeflate=1.17=h0b41bf4_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=13.3.0=h77fa898_1
  - libgcc-ng=13.3.0=h69a702a_1
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=13.3.0=h77fa898_1
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - libnsl=2.0.0=hd590300_1
  - libpng=1.6.39=h753d276_0
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=2.1.2=py39h72bdee0_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.1.0=h9202a9a_1
  - mpmath=1.2.1=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - networkx=3.0=pyhd8ed1ab_0
  - numpy=1.23.5=py39h3d75532_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.4.1=h7b32b05_0
  - packaging=23.0=pyhd8ed1ab_0
  - pillow=9.4.0=py39h2320bf1_1
  - pip=24.2=py39h06a4308_0
  - platformdirs=3.0.0=pyhd8ed1ab_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.16=h2782a2a_0_cpython
  - python_abi=3.9=5_cp39
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.2=py39hcd6043d_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.2=pyhd8ed1ab_1
  - scipy=1.10.1=py39h6183b62_3
  - setuptools=75.8.0=pyhff2d567_0
  - sqlite=3.40.0=h4ff8645_0
  - tbb=2021.9.0=hf52228f_0
  - tk=8.6.12=h27826a3_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=h166bdaf_4
  - zstandard=0.19.0=py39h6e5214e_2
  - zstd=1.5.2=hfc55251_7
  # Ensure modern C++ runtime is available in the env to satisfy SciPy's GLIBCXX requirements
  - libstdcxx-ng
  - libgcc-ng
  - pip:
      - https://data.dgl.ai/wheels/dgl_cu113-0.9.1.post1-cp39-cp39-manylinux1_x86_64.whl
      - torch==1.12.1+cu113
      - torchaudio==0.12.1+cu113
      - torchvision==0.13.1+cu113
      - --extra-index-url https://download.pytorch.org/whl/cu113
      - fsspec==2024.12.0
      - joblib==1.4.2
      - pandas==2.2.3
      - portalocker==3.1.1
      - psutil==6.1.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - rdkit==2023.03.2
      - scikit-learn==1.6.1
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - unzip==1.0.0
prefix: /root/miniconda3/envs/ehign
